### ISSUE TITLE
Not an issue but an information 👀

### ISSUE THREAD

**Issue by biertester** [GaisaiYuno/magicbook2019-ryzen3500u-hackintosh#1]
Hey man! Look at this: https://www.reddit.com/r/hackintosh/comments/11aqgad/mac_os_big_sur_ryzen_5_3500u_laptop_vega_8_igpu/?utm_source=share&utm_medium=ios_app&utm_name=iossmf you can now use integrated graphics for the MagicBook 2019 on macOS (Big Sur only for now) using NootedRed (newer name of WhateverRed) check it out 👀

**Comment by biertester** [comment]
Yeay! Good luck to you :), my laptop is the same as yours 👀

**Comment by biertester** [comment]
And I think you can test using the latest updated BIOS of the Laptop, coz there’s some changes that needs to be done to successfully boot I think ? I don’t know

**Comment by GaisaiYuno** [comment]
Greetings from MacOS Big Sur! It seemed that Big Sur supports AMD CPU and is similar to Catalina in many ways. However, the graphics is not functioning. Including the NootedRed kext will produce a kernel panic error and I'm currently adjusting the booting args. P.S. The start up process was extremely painful as it might take 10-20 trials to get a success boot.

**Comment by GaisaiYuno** [comment]
> Greetings from MacOS Big Sur! It seemed that Big Sur supports AMD CPU and is similar to Catalina in many ways. However, the graphics is not functioning. Including the NootedRed kext will produce a kernel panic error and I'm currently adjusting the booting args. P.S. The start up process was extremely painful as it might take 10-20 trials to get a success boot.

It stops at random positions near "AppleNvme"

**Comment by GaisaiYuno** [comment]
![image](https://user-images.githubusercontent.com/52853137/227674156-01c5cc2f-3f1b-4c96-b844-31de8b1a4e61.png)

**Comment by GaisaiYuno** [comment]
And I've upgraded my ssd to WD SN570 but the results are totally same.

**Comment by biertester** [comment]
Hi! Just so you know: the kext only works once Big Sur is installed, it is normal if it didn’t work for you on the installer, and u can check the boot args of the man from the reddit link I shared u!

**Comment by GaisaiYuno** [comment]
Breaking news! I've applied the latest nootedred kext and it worked! It recognized the gpu as "AMD Radeon Vega 8 1GB" and it is totally usable. There are also some improvements. I'm able to adjust screen brightness, read battery percentage. Most importantly, the probability for a success boot comes to 100%!  However, the screen would be dead after plugging in the external monitor for a few minutes and you have to manually reboot the system. 
![截屏2023-06-18 下午4 14 45](https://github.com/GaisaiYuno/magicbook2019-ryzen-hackintosh/assets/52853137/55baeb71-bfa9-44a5-b885-a52a0a91fa05)

I'm currently trying to fix trackpad, audio, and bluetooth.

**Comment by biertester** [comment]
Hey! Glad to hear that! That means that you can update your EFI folder in here (github) soon 👀 cool!

**Comment by GaisaiYuno** [comment]
Enabling Bluetooth is difficult because Bluetooth involves the usb controller, however Apple introduced a limit of up to 15 ports after BigSur 11.3, so you need to disable XHC1 through the UMAF tool (this will cause the right USB port to be unusable), after that generate UTBmap.kext under windows so that you can drive the left usb- C port, usb-A port and Bluetooth interface. After updating to the latest version of NootRed, the problem of insufficient video memory and sudden freezing of the screen was solved. After that, the work is mainly to drive the touchpad and test the sleep issue. I believe that the configuration is now as well as close to perfect and should update the EFI file in a few days.

**Comment by biertester** [comment]
Wow! Great job man! 😎

Le mer. 21 juin 2023 à 17:58, Steven Meng ***@***.***> a
écrit :

**Comment by GaisaiYuno** [comment]
EFI updated

**Comment by vasilisfr** [comment]
Awesome work! I have the same laptop, trying to install Big Sur with your configuration!
