### ISSUE TITLE
请问，这样要怎么处理呢

### ISSUE THREAD

**Issue by zmybest** [GaisaiYuno/magicbook2019-ryzen3500u-hackintosh#3]
![20230715_011730_HDR](https://github.com/GaisaiYuno/magicbook2019-ryzen3500u-hackintosh/assets/33447519/71b41bca-9c1e-4c07-ba7e-0971dca0dec4)

**Comment by zmybest** [comment]
我的硬盘是sn720，不是pm981

**Comment by zmybest** [comment]
我换了U盘，好了，但是又卡在另外一个代码上了
![Uploading 20230719_011045_HDR.jpg…]()

**Comment by zmybest** [comment]
![20230719_011045_HDR](https://github.com/GaisaiYuno/magicbook2019-ryzen3500u-hackintosh/assets/33447519/eeadf164-07ad-40e8-90c1-2bc79c8a3291)

**Comment by rct-yspk** [comment]
> ![20230719_011045_HDR](https://user-images.githubusercontent.com/33447519/254426282-eeadf164-07ad-40e8-90c1-2bc79c8a3291.jpg)

same shit

**Comment by zmybest** [comment]
![20230726092955](https://github.com/GaisaiYuno/magicbook2019-ryzen3500u-hackintosh/assets/33447519/1c8af817-5bfa-4679-957a-0ba912e53bee)
a few minutes later

**Comment by zmybest** [comment]
安装时禁用NootedRed即可，安装完成再开启（disabled NootedRed during installing）
